docs/visualizations/two-axes-charts/line-chart.mdx
packages/client/svelte/src/lib/internal/ui/chart/_Echarts.svelte
packages/client/svelte/src/lib/ui/popover/popover-content.svelte
packages/client/svelte/src/lib/ui/select/select-content.svelte

Fix internal link in chart docs

---

docs/guides/getting-started/installation.mdx
docs/guides/getting-started/windows-compatibility.mdx
docs/mint.json

New docs on how to run Latitude on Windows machines.

docs: windows compatibility

---

.changeset/dull-pants-pull.md
packages/connectors/postgresql/package.json
packages/connectors/postgresql/rollup.config.mjs
packages/connectors/postgresql/src/index.test.ts
packages/connectors/postgresql/src/index.ts
packages/connectors/postgresql/vitest.config.js
pnpm-lock.yaml

Implements ssl support for the postgres connector

minor: added ssl support to postgres connector

---

.changeset/tough-glasses-search.md
packages/connectors/snowflake/rollup.config.mjs

minor: remove snowflake commonjs build

---

.changeset/selfish-cups-study.md
docs/sources/bigquery.mdx
packages/connectors/bigquery/src/index.ts

- Fixes bug parsing results from bigquery
- Clarifies documentation and code about service account and oauth credentials
Related: https://github.com/latitude-dev/latitude/issues/138

fix: bigquery results parsing

---

.changeset/fast-frogs-boil.md
.github/workflows/e2e.yml
packages/cli/src/cli.ts
packages/cli/src/commands/dev/runDev.ts
packages/cli/src/commands/start/index.ts
packages/cli/src/commands/start/questions.ts
packages/cli/tests/e2e/dev.cjs
packages/cli/tests/e2e/start.cjs

Runs an acceptance test in CI that starts a default project and runs the local server with the production build of the CLI.

feature: acceptance tests CLI

---

.changeset/loud-ravens-carry.md
packages/cli/package.json
packages/cli/rollup.config.mjs
packages/cli/src/commands/constants.ts
packages/cli/src/commands/index.ts
packages/cli/src/commands/start/questions.ts
packages/cli/src/index.ts
packages/cli/src/lib/boxedMessage.ts
packages/cli/src/lib/configStore/index.ts
packages/cli/src/lib/decorators/versionCheck/index.test.ts
packages/cli/src/lib/decorators/versionCheck/index.ts
packages/cli/src/lib/telemetry/index.ts
pnpm-lock.yaml

Checks for cli version mismatches and displays a prompt to update.
Solves https://github.com/latitude-dev/latitude/issues/153

feature: cli version check on any command

---

.changeset/spotty-phones-kiss.md
packages/cli/src/commands/dev/runDev.ts
packages/cli/src/lib/telemetry/index.ts

We are overusing this feature.

minor: reduce the number of boxed messages in CLI

---

docs/guides/embed/iframe.mdx
docs/queries/logic/parameters.mdx

We implemented [signed params](https://github.com/latitude-dev/latitude) and this is just the documentation for it

Document how to use signed parameters

---

.changeset/great-pianos-decide.md
packages/cli/src/commands/build/index.ts
packages/cli/src/commands/dev/runDev.ts
packages/cli/src/commands/run/index.ts
packages/cli/src/commands/start/index.ts
packages/cli/src/commands/update/index.ts
packages/cli/src/config.ts
packages/cli/src/lib/decorators/versionCheck/index.ts
packages/cli/src/lib/getAppVersions.test.ts
packages/cli/src/lib/getAppVersions.ts
packages/cli/src/lib/latitudeConfig/findOrCreate.test.ts
packages/cli/src/lib/latitudeConfig/findOrCreate.ts
packages/cli/src/lib/latitudeConfig/getLatestVersion.ts
packages/cli/src/lib/setupApp/cloneAppFromNpm.ts
packages/cli/src/lib/setupApp/installDependencies.ts
packages/cli/src/lib/sync/syncDependencies/index.ts

Solve this https://github.com/latitude-dev/latitude/issues/186

Show in production NPM install progress and also remove pkgManager abstraction

---

.changeset/honest-suns-count.md
apps/server/src/lib/query_service/find_or_compute.test.ts
apps/server/src/lib/query_service/find_or_compute.ts
apps/server/src/routes/api/queries/[...query]/+server.ts
apps/server/src/routes/api/queries/[...query]/castValue.ts
apps/server/src/routes/api/queries/[...query]/getEncryptedParams.ts
apps/server/src/routes/api/queries/[...query]/getQueryParams.ts
apps/server/src/routes/api/queries/[...query]/server.test.ts

The path resolution algorithm was broken when queries and sources were added in subfolders

fix: queries in subfolders weren't working

---

.changeset/giant-ads-glow.md
.changeset/lucky-onions-compare.md
apps/server/src/routes/api/queries/[...query]/+server.ts
apps/server/src/routes/api/queries/[...query]/getEncryptedParams.ts
apps/server/src/routes/api/queries/[...query]/getQueryParams.ts
apps/server/src/routes/api/queries/[...query]/specialParams.test.ts
packages/client/core/src/constants.ts
packages/client/core/src/data/api.ts
packages/query_result/.eslintrc.cjs
packages/query_result/package.json
packages/query_result/src/index.test.ts
packages/query_result/src/index.ts
packages/query_result/vitest.config.js
pnpm-lock.yaml

Exposes a new __download extra param to download a query result as a csv excel

feature: csv exports

---

docs/visualizations/others/funnel-chart.mdx
docs/visualizations/others/pie-chart.mdx
docs/visualizations/tables/table.mdx
docs/visualizations/two-axes-charts/area-chart.mdx
docs/visualizations/two-axes-charts/bar-chart.mdx
docs/visualizations/two-axes-charts/line-chart.mdx
docs/visualizations/two-axes-charts/mixed-types-chart.mdx
docs/visualizations/two-axes-charts/scatter.mdx

docs: improved chart previews

---

.changeset/big-lobsters-smell.md
apps/server/src/lib/autoimports/forms/Select/index.svelte
packages/client/svelte/src/lib/ui/combobox/index.svelte

Left align popover with it's trigger. Expose the prop.

fix: Select combobox alignment

---

docs/guides/embed/react-embed.mdx
docs/mint.json

Document <LatitudeEmbed />

---

apps/server/src/lib/stores/queries.test.ts
apps/server/src/lib/stores/queries.ts
docs/views/basics/running-queries.mdx
docs/views/components/visualizations/funnel-chart.mdx
docs/views/components/visualizations/pie-chart.mdx
docs/views/components/visualizations/scatter.mdx
tools/latitude-vscode/vscode-test/sampleWorkspace/latitudeProject/views/index.html
tools/latitude-vscode/vscode-test/sampleWorkspace/notLatitudeProject/views/index.html

This resolve this issue: https://github.com/latitude-dev/latitude/issues/254

Replace `reactiveToParms` with `reactToParams`

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation_request.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/source_connector.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md

Fix this issue https://github.com/latitude-dev/latitude/issues/195

Add contributing and coc documents also template issues

---

docs/guides/getting-started/windows-compatibility.mdx

docs: added build tools tip to windows compatibility docs

---

docs/guides/getting-started/troubleshooting.mdx
docs/mint.json

docs: added troubleshooting section

---

.github/workflows/cla.yml
cla.md

Github action to prompt new contributors to sign the CLA.

feat: added cla github action

---

.changeset/sharp-ravens-applaud.md
.gitmodules
docs/guides/examples/api.mdx
docs/guides/examples/basic-example.mdx
packages/cli/src/commands/start/cloneTemplate.ts
packages/cli/src/commands/start/questions.ts

New template name

---

.changeset/chatty-drinks-switch.md
packages/cli/src/cli.ts
packages/cli/src/commands/cloud/tokens/create/index.ts
packages/cli/src/lib/telemetry/events.ts

Tokens allow authentication in non-tty environments like CI

feature: create token command

---

.changeset/weak-icons-think.md
packages/cli/src/commands/cloud/deploy/index.ts

What is in the title
This part is dependent on the server change but I think is fine if we merge it no?

Unify api parameter when deploying and call it always app

---

.changeset/quiet-dragons-fix.md
packages/cli/src/commands/cloud/deploy/index.ts
packages/cli/src/commands/constants.ts
packages/cli/src/commands/start/index.ts

Little GitHub stars banner in start/deploy commands in CLI ⭐️

⭐️ Little GitHub stars banner in start/deploy commands in CLI

---

.changeset/mean-crews-raise.md
packages/client/core/src/theme/ui/button/index.ts
packages/client/svelte/src/lib/ui/button/button.stories.svelte
packages/client/svelte/src/lib/ui/button/index.svelte
packages/client/svelte/src/lib/ui/combobox/index.svelte

Fix comobox button text overflow it's parent's width when space is reduced

---

.changeset/curvy-grapes-suffer.md
docs/guides/getting-started/introduction.mdx
docs/queries/basics/file-structure.mdx
docs/react/getting-started/introduction.mdx
docs/snippets/trackingpixel.mdx
docs/sources/how-to-configure-sources.mdx
docs/views/basics/what-are-views.mdx
packages/cli/package.json
pnpm-lock.yaml

Add anonymous tracking of cli installs

patch: added install analytics tracking

---

docs/guides/getting-started/introduction.mdx
docs/queries/basics/file-structure.mdx
docs/react/getting-started/introduction.mdx
docs/sources/how-to-configure-sources.mdx
docs/views/basics/what-are-views.mdx

Nothing interesting tbh, just repositioning the pixel in the docs pages.

minor: repositioned tracking pixel in docs

---

.changeset/honest-turkeys-develop.md
apps/server/src/lib/autoimports/forms/Select/index.svelte
packages/client/core/src/theme/ui/button/index.ts
packages/client/core/src/theme/ui/input/index.ts

What the title says
https://www.loom.com/share/a41b99075a054aa0bf342e130931f366?sid=90631cb8-db78-46c1-bd56-b2e9ee3c2a02

patch: fix some select component styles affecting total width in some situations

---

docs/snippets/charts/_properties/common.mdx
docs/views/components/visualizations/funnel-chart.mdx
docs/views/components/visualizations/pie-chart.mdx

Added width and height attributes to visualizations config in docs

Added height and width properties to visualizations docs

---

.changeset/olive-cycles-double.md
.github/workflows/pre-release.yml
CONTRIBUTING.md
packages/cli/src/cli.ts
packages/cli/src/commands/start/index.ts
packages/cli/src/commands/update/index.ts
packages/cli/src/lib/getAppVersions.test.ts
packages/cli/src/lib/getAppVersions.ts
packages/cli/src/lib/latitudeConfig/create.ts
packages/cli/src/lib/latitudeConfig/findOrCreate.ts
packages/cli/src/lib/latitudeConfig/getLatestVersion.ts
packages/cli/src/lib/setupApp/index.ts

We changed the branch from next to canary. This change reflects on that

Adjust CONTRIBUTING.md and pre-release.yml CI script to point to canary branch

---

.changeset/tame-jeans-doubt.md
packages/cli/src/commands/cloud/deploy/index.ts

Adds counters for each backend message

patch: slight improvement to cli deploy command

---

.changeset/lovely-drinks-complain.md
.github/workflows/test.yml
apps/server/scripts/materialize_queries/index.ts
packages/cli/src/cli.ts
packages/cli/src/commands/materialize/index.ts
packages/cli/src/lib/telemetry/events.ts
packages/connectors/compiler/package.json
packages/connectors/compiler/rollup.config.mjs
packages/connectors/compiler/src/compiler/index.ts
packages/connectors/compiler/src/compiler/utils.ts
packages/connectors/materialized/rollup.config.mjs
packages/connectors/materialized/src/index.ts
packages/source_manager/src/materialize/drivers/StorageDriver.test.ts
packages/source_manager/src/materialize/drivers/StorageDriver.ts
packages/source_manager/src/materialize/findAndMaterializeQueries.test.ts
packages/source_manager/src/materialize/findAndMaterializeQueries.ts
packages/source_manager/src/materialize/index.ts
packages/source_manager/tsconfig.json
pnpm-lock.yaml

Implement `materialize` CLI command to be used in user's machine or while building docker image

Materialize query CLI command

---

.changeset/giant-fishes-tie.md
apps/server/vite.config.ts
packages/client/core/src/data/api.ts
packages/client/svelte/src/lib/ui/combobox/index.svelte

While we did QA for canary release we found these issues

QA fixes while testing canary

---

docs/mint.json
docs/queries/advanced/config.mdx
docs/queries/advanced/materialized-queries.mdx
docs/queries/logic/loops.mdx
docs/snippets/queries/config.mdx
docs/sources/additional-config.mdx
docs/sources/duckdb.mdx
docs/views/components/inputs/select.mdx

Documentation for upcoming materialized queries

Add documentation for materialize queries

---

.changeset/poor-fireants-warn.md
packages/cli/src/commands/version/index.ts

I forgot [in this PR](https://github.com/latitude-dev/latitude/pull/476) to add info about installed version of the app if it's installed

Add to latitude -v also info about installed version of the app

---

docs/react/getting-started/installation.mdx

Updated the React getting started to the correct installation commands and snippets.
Updated the React getting started guide with the correct commands.
[Slack thread](https://trylatitude.slack.com/archives/C06RP64CSCQ/p1717503480856129)

chore: Update installation.mdx

---

.changeset/brown-swans-battle.md
.changeset/hip-colts-sell.md
.changeset/hungry-adults-jump.md
.changeset/ten-masks-tap.md
.changeset/tender-years-rhyme.md
.changeset/wise-lions-breathe.md
apps/server/scripts/materialize_queries/index.ts
apps/server/vite.config.ts
packages/cli/core/src/commands/run/index.ts
packages/cli/core/src/lib/v1.schema.json
packages/cli/display_table/src/app.tsx
packages/connectors/duckdb/package.json
packages/connectors/duckdb/src/index.ts
packages/source_manager/src/manager/findAndMaterializeQueries.test.ts
packages/source_manager/src/manager/index.ts
packages/source_manager/src/types.ts
packages/storage_driver/package.json
packages/storage_driver/src/drivers/base.ts
packages/storage_driver/src/drivers/disk/DiskDriver.test.ts
packages/storage_driver/src/drivers/disk/index.ts
packages/storage_driver/src/drivers/index.ts
packages/storage_driver/src/drivers/s3/index.ts
packages/storage_driver/src/types.ts
pnpm-lock.yaml

S3 storage driver

---

.changeset/ten-chefs-cheat.md
packages/cli/core/src/commands/cloud/deploy/docker/DockerfileTemplate.ts
packages/cli/core/src/lib/v1.schema.json
packages/cli/core/src/templates/Dockerfile.ts

Some fixes to make cloud deploy work

---

packages/llm_manager/src/model/supportedMethods/index.ts
packages/llm_manager/src/model/supportedMethods/readQuery.ts

Missed some functions on Dynamic Prompts

Dynamic prompts missing changes

---

.changeset/famous-mayflies-attend.md
packages/client/core/src/theme/assets/latitude.css
packages/client/core/src/theme/ui/table/index.ts
packages/client/svelte/src/lib/internal/ui/Table/Table.svelte

Fix showing JSON columns in Svelte Table

---

README.md
docs/guides/deploy/nodejs.mdx
docs/guides/examples/basic-example.mdx

Small documentation fixes
