- docs/guides/examples/templates.mdx
- docs/mint.json
Adds links to templates in the examples section to help people get started with more complex projects or particular uses cases.
> minor: added templates in the examples section of docs

- .changeset/silent-kiwis-sniff.md
- .github/workflows/linter.yml
- .github/workflows/test.yml
- packages/connectors/athena/package.json
- packages/connectors/base/package.json
- packages/connectors/bigquery/package.json
- packages/connectors/databricks/package.json
- packages/connectors/duckdb/package.json
- packages/connectors/mssql/package.json
- packages/connectors/mysql/package.json
- packages/connectors/postgresql/package.json
- packages/connectors/snowflake/package.json
- packages/connectors/sqlite/package.json
- packages/connectors/trino/package.json
There's really no point in having peer dependencies between latitude packages. Let's remove them.
> minor: remove peer dependencies between latitude packages

- .github/workflows/release.yml
- package.json
Adds necessary configuration for automatic releases using changesets github action. This action will also automatically create the github release tags upon publishing. Here are their [docs](https://github.com/changesets/action?tab=readme-ov-file#inputs).
> feature: add automatic releases from CI

- .changeset/four-carpets-fly.md
- packages/cli/src/commands/dev/runDev.ts
They are harmless and only increase noise
> minor: ignore cli spawn process warnings

- .changeset/hungry-toes-care.md
- apps/server/src/lib/autoimports/RunButton/index.svelte
- apps/server/src/lib/stores/queries.ts
- apps/server/src/routes/api/queries/[...query]/+server.ts
- apps/server/src/routes/api/queries/[...query]/server.test.ts
- packages/client/core/src/stores/queries.ts
Solved problems:
- RunButton didn't call any refetch if no queries were specified
- All initial fetches were using `force: true`
- The force tag wasn't being added to force requests
Also changed the method of sending the force tag from a `__force` parameter to a `X-Force-Refetch` header.
> Fix: queries not refetching

- .changeset/yellow-suns-ring.md
- docs/sources/athena.mdx
- packages/connectors/athena/src/index.ts
Added option to indicate credentials via env vars. Made workgroup a mandatory field. Fixed documentation
Related: https://github.com/latitude-dev/latitude/issues/138
> feature: athena fixes

- .changeset/wild-planets-thank.md
- packages/cli/src/commands/update/index.ts
- packages/cli/src/config.ts
- packages/cli/src/lib/getAppVersions.test.ts
- packages/cli/src/lib/getAppVersions.ts
- packages/cli/src/lib/latitudeConfig/findConfigFile.ts
- packages/cli/src/lib/latitudeConfig/findOrCreate.test.ts
- packages/cli/src/lib/latitudeConfig/findOrCreate.ts
- packages/cli/src/lib/latitudeConfig/getLatestVersion.ts
- packages/cli/src/lib/latitudeConfig/updateVersion.ts
We've seen some users experiencing errors fetching latitude's latest versions from npm. I suspect is because we are hard crashing when the npm view process outputs on stderr, which we should not, as it is known npm often outputs harmless warnings to stderr.
> fix: latest version fix

- .changeset/nice-lions-rhyme.md
- packages/cli/src/lib/telemetry/index.test.ts
- packages/cli/src/lib/telemetry/index.ts
- packages/cli/tests/e2e/start.cjs
Fix this issue https://github.com/latitude-dev/latitude/issues/177
> Avoid showing telemetry UI permissions twice and add tests

- .changeset/heavy-foxes-taste.md
- packages/connectors/mysql/src/index.test.ts
- packages/connectors/mysql/src/index.ts
We were not properly closing mysql connections after running the query. Ideally we would need to change our query system so that we maintain a pool of connections open but this requires some more work. In the meantime this is a good enough compromise.
fixes #194
> fix: properly closing mysql connection

- .changeset/pink-toes-lie.md
- packages/cli/src/commands/dev/index.ts
- packages/cli/src/commands/dev/runDev.ts
- packages/cli/src/commands/start/index.ts
- packages/cli/src/lib/latitudeConfig/InstalledVersionChecker.ts
- packages/cli/src/lib/telemetry/index.ts
- packages/cli/tests/e2e/start.cjs
- turbo.json
Fix template selector not shown when creating a new project
> Fix show template selector when init a project with CLI

- .changeset/four-taxis-walk.md
- apps/server/package.json
- apps/server/src/lib/stores/queries.ts
- docs/queries/logic/parameters.mdx
- pnpm-lock.yaml
Instead of being just a boolean, `reactiveToParams` now allows using a `number` too, to define the debounce time between param updates before calling a refetch.
> Allow to set a debounce time on reactiveToParams option.

- pnpm-lock.yaml
- tools/latitude-vscode/package.json
We are requiring the latest vscode version (1.87), but some vscode forks are a bit behind. Relaxing our requirements a bit to add support for those forks.
Related #212
> feature: relax vscode version requirements a bit

- .changeset/silent-chairs-talk.md
- .github/workflows/release.yml
- packages/cli/package.json
- packages/cli/rollup.config.mjs
- packages/cli/src/cli.ts
- packages/cli/src/integrations/sentry.test.ts
- packages/cli/src/integrations/sentry.ts
- packages/cli/src/lib/telemetry/index.test.ts
- packages/cli/src/lib/telemetry/index.ts
- pnpm-lock.yaml
- turbo.json
Fix this issue https://github.com/latitude-dev/latitude/issues/171
> Add Sentry to CLI

- .changeset/witty-lizards-cough.md
- apps/server/scripts/run_query/index.ts
- apps/server/scripts/run_query/result_display.ts
- packages/cli/src/commands/run/index.ts
Latitude run was working by invoking the `query` script in the server app. The invoking command was `npm run query --watch <queryPath> <queryParams>`. This invoked the script with the following arguments: `["--watch", <queryPath>, <queryParams>]` (of course)
For some reason I do not understand, now npm decided not to pass dashed flags to the script, so it now was invoking the script with `[<queryPath>, <queryParams>]`, completely ignoring the `watch` flag.
I have changed the script so that now it expects 3 arguments, instead of 2 arguments and a flag. Not it must be invoked like this: `npm run query <queryPath> <watch:true|false> <queryParams>`
> Fix: Latitude run watch not working

- .changeset/hip-stingrays-sniff.md
- apps/server/package.json
- apps/server/src/lib/stores/queries.test.ts
- apps/server/src/lib/stores/queries.ts
- pnpm-lock.yaml
If `reactiveToParams` is active, don't debounce if the results have already been fetched beforehand. Debounce only the actual fetch requests.
> Fix: reactiveToParams debouncing even when results are cached

- .changeset/nine-games-attack.md
- apps/server/package.json
- apps/server/src/hooks.server.ts
- apps/server/src/lib/query_service/find_or_compute.ts
- apps/server/src/lib/server/connectorManager.ts
- apps/server/src/lib/server/shutdown.ts
- packages/cli/src/config.ts
- packages/connectors/athena/src/index.ts
- packages/connectors/base/src/index.ts
- packages/connectors/clickhouse/src/index.ts
- packages/connectors/databricks/src/index.ts
- packages/connectors/duckdb/src/index.ts
- packages/connectors/mssql/src/index.ts
- packages/connectors/mysql/src/index.test.ts
- packages/connectors/mysql/src/index.ts
- packages/connectors/postgresql/src/index.ts
- pnpm-lock.yaml
`BaseConnector` is already managing the connector pools lifespan. It runs the `connect` method before running a query, then runs that query and any other one that is included in it, and finally runs the `disconnect` method afterwards.
This allows to keep the `BaseConnector` instance alive whenever we want, without having to worry about having open connections.
Although this is the default behaviour, most connectors do not have any implementation for these `connect` and `disconnect` methods, which they should.
> Fix: Manage connection lifespan

- .changeset/proud-icons-worry.md
- apps/server/scripts/run_query/result_display.ts
CLI run command always cut off the last two results from the table.
```sql
{@const ids = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}
{#each ids as i}
{#if i > 1}UNION ALL{/if}
SELECT {i} AS id
{/each}
```
Before vs after:
> Fix: CLI Table cuts off last two results

- .changeset/flat-cougars-deliver.md
- apps/server/plugins/latitude.ts
- apps/server/vite.config.ts
- docs/queries/logic/parameters.mdx
Allow to use a reactive `param('name')` function in the Views.
Usage example:
```jsx
<Row>
<Text.H1 class="font-bold">Netflix Analysis</Text.H1>
</Row>
<Row>
<Text.H3 class="font-bold">From {param('start_year')} to {param('end_year')}</Text.H3>
</Row>
<Row>
<Text.H4>This data app shows titles added to Netflix over the years.</Text.H4>
</Row>
<Row class="mt-4 md:mt-8 gap-4">
<Input param="start_year" type="number" value="2000" />
<Input param="end_year" type="number" value="2024" />
</Row>
```
> Feature: use param function on views

- .changeset/ninety-penguins-invent.md
- examples/sample-react/src/app.tsx
- examples/sample-react/src/examples/Embedding/index.tsx
- packages/client/react/rollup.config.mjs
- packages/client/react/src/index.ts
- packages/client/react/src/webcomponents/index.ts
- packages/client/webcomponents/package.json
- packages/client/webcomponents/src/index.ts
- packages/client/webcomponents/stencil.config.ts
- pnpm-lock.yaml
We use StencilJS in our @latitude-data/webcomponents. StencilJS help use author webcomponents and a thin wrapper in React. But in the future we can add support for Vue or Svelte. The problem was that I develop the iframe integration and it worked in developent but when I deployed a production react example using our `LatitudeEmbed` component I realized build was broken. This pr try to produce a valid Stencil + React build for our component. We use `dist-custom-elements` as StencilJS target to be use together with the React wrapper generated by StencilJS
> Fix StencilJS webcomponents build

- .changeset/smooth-monkeys-kick.md
- examples/sample-react/src/app.tsx
- packages/client/react/rollup.config.mjs
- packages/client/react/src/index.ts
- packages/client/webcomponents/package.json
- packages/client/webcomponents/stencil.config.ts
Everything build ok in development and build + preview but when testing the full story deploying example react app to Vercel build fail saying "has no exported member 'defineCustomElements'"
I hope this fix the problem
> Fix missing `defineCustomComponents` from @latitude-data/webcomponents

- .changeset/moody-phones-swim.md
- packages/client/react/package.json
- pnpm-lock.yaml
I wasn't able to deploy to Vercel example react app with `@latitude-data/webcomponents` + `@latitude-data/react` packages. That means something is still broken
The error I see in Vercel logs is this
This is just a quick test but I need to do a full release to test it from npm. I don't think this is going to fix it because is just adding a missing line in the `pnpm-lock.json` file but it worth a try
If this doesn't work my next idea is to include as dependency `@stencil/core` in `@latitude-data/react` package. Apparently Stencil is used at runtime. Which kind of makes sense but I didn't expected.
> Fix Error: [vite]: Rollup failed to resolve import "@stencil/core/internal/client"

- .changeset/hot-olives-double.md
- packages/client/webcomponents/stencil.config.ts
When I deploy example react app using published packages `@latitude-data/react` the building of the app fails saying "Error: [vite]: Rollup failed to resolve import "@stencil/core/internal/client" from". Acording to Stencil Docs: https://stenciljs.com/docs/custom-elements#externalruntime You can ship your component with stencil runtime. This is what I'm trying here
> Fix bundle error when deploying React example app

- .changeset/wild-eggs-drive.md
- apps/server/src/lib/iframeEmbedding.ts
- packages/client/webcomponents/src/components/latitude-embed/latitude-embed.tsx
- packages/embedding/src/iframe-messages.ts
- packages/embedding/src/index.ts
- packages/embedding/src/types.ts
We were using the same event name when the param is changed from react host app than when is changed from inside view and this was causing an infinite loop 💀
> Use different event in embedding when the URL param change from inside the view

- .changeset/lemon-ligers-raise.md
- apps/server/.gitignore
- apps/server/plugins/queriesWatcher.ts
- apps/server/src/lib/query_service/find_or_compute.ts
- apps/server/src/routes/+layout.ts
- docs/views/basics/what-are-views.mdx
- packages/cli/src/lib/sync/index.ts
- packages/cli/src/lib/sync/syncQueries/index.ts
- packages/cli/src/lib/sync/syncStaticFiles/index.test.ts
- packages/cli/src/lib/sync/syncStaticFiles/index.ts
ALL files inside `views` that are not `html` files will be copied to the `static` directory in the app folder. The only exception are hidden files and directories (starting with a dot).
We were using a `static/latitude` folder for the queries, but since it can now conflict with the user's view files, I changed it to `static/.latitude`, since hidden directories are not copied.
> Static files support for views

- packages/cli/src/lib/sync/syncViews/index.ts
For some reason, using the regex with chokidar's `ignored` tag is making it ignore all file changes. (The regular expression is `/^(?!.*index\.html$).*$/`, where it should match any file except for `index.html` files)
We instantiate the `watcher` like this:
```ts
await watcher(viewsDir, syncFn, {
ignored: IGNORED_FILES_REGEX,
})
```
and the `syncFn` has this at the start:
```ts
if (IGNORED_FILES_REGEX.test(relativeSrcPath)) return
```
It should just do the same, so it should not be needed. However, with the ignored tag in the watcher, no files at all are triggering the syncFn. With that tag ignored, every file change does trigger de function, but then it is correctly filtered by the regex. 
Any idea why is it working when manually filtering but not when used as a chokidar option?
Also, …
> Fix: chokidar is not ignoring correctly

- .changeset/twelve-parents-fold.md
- packages/cli/src/lib/sync/syncStaticFiles/index.ts
- packages/cli/src/lib/sync/syncViews/index.test.ts
- packages/cli/src/lib/sync/syncViews/index.ts
A user tried to build a project without `views` folder. Not having a views folder is legit so we need to handle this case
> Fix LATITUDE-DATA-CLI-7 avoid failing CLI build when no views folder

- .changeset/silly-beers-lick.md
- apps/server/scripts/run_query/index.ts
- apps/server/scripts/run_query/result_display.ts
- docs/guides/development/latitude-cli.mdx
- packages/cli/src/cli.ts
- packages/cli/src/commands/run/index.ts
- packages/cli/src/config.ts
- packages/cli/src/types.ts
- packages/cli/tests/e2e/dev.cjs
- packages/cli/tests/e2e/start.cjs
- pnpm-lock.yaml
Added a `--debug` flag to the `latitude run` command to see the compiled query without actually running it.
Also, all other `--debug` flags from the CLI, which allowed to print console logs, have been been renamed to `--verbose`.
> Feature: See compiled queries from CLI

- .changeset/brown-mangos-marry.md
- apps/server/src/lib/stores/setUrlParam.test.ts
- apps/server/src/lib/stores/viewParams.ts
We want to avoid URLs in data apps with empty params like `?search=$text:`. Only when `search` has a non-empty value would appear in the URL
https://github.com/latitude-dev/latitude/issues/255
> Remove empty params when data apps load.

- docs/queries/advanced/interpolation.mdx
- docs/queries/basics/sql-syntax-basics.mdx
- docs/queries/logic/if-else.mdx
- docs/queries/logic/loops.mdx
I removed the docs we had on basic regular SQL syntax (I think that we can skip that part, since our userbase most likely already knows basic SQL syntax, and we already link to each source's documentation). 
Instead, in that same place I added documentation on our custom syntax: what it is, how it works, and what can do.
> Improved docs for SQL syntax

- .changeset/modern-nails-punch.md
- packages/cli/package.json
- packages/cli/rollup.config.mjs
- packages/cli/src/cli.ts
- packages/cli/src/commands/update/index.ts
- packages/cli/src/lib/setupApp/index.test.ts
- packages/cli/src/lib/setupApp/index.ts
- packages/cli/src/lib/sync/syncViews/index.test.ts
- packages/cli/src/lib/updateApp/index.ts
- packages/cli/src/templates/Dockerfile.template
- packages/cli/src/templates/dockerignore.template
- packages/cli/src/types.d.ts
- packages/cli/tsconfig.json
- packages/cli/vitest.config.js
- pnpm-lock.yaml
Right now there's an implicit dependency between our templates and CLI via the docker configuration that the templates include. From now on CLI is in charge of including package.json, dockerignore and dockerfile files, effectively eliminating this hidden dependency.
> feature: cli creates dockerfiles

- .changeset/cold-lies-cheat.md
- apps/server/scripts/run_query/index.ts
- apps/server/src/lib/query_service/find_or_compute.test.ts
- apps/server/src/lib/query_service/find_or_compute.ts
- apps/server/src/routes/api/queries/[...query]/+server.ts
- apps/server/src/routes/api/queries/[...query]/server.test.ts
- packages/source_manager/src/index.test.ts
- packages/source_manager/src/index.ts
- packages/source_manager/src/lib/findSourceFile/index.test.ts
- packages/source_manager/src/source.test.ts
In a prior commit we introduced a regression that caused nested queries to not be found by the CLI during development. This commit fixes this issue.
fixes #348
> hotfix: nested query folders not found

- .github/workflows/pre-release.yml
- .prettierignore
- CONTRIBUTING.md
- apps/server/scripts/run_query/index.ts
We want to develop with confidence and have a pre-release flow so we can QA our changes before publishing in npm.
> Introduce pre-release workflow to ship alpha versions of our packages

- .changeset/bright-rules-try.md
- .github/workflows/e2e.yml
- .github/workflows/linter.yml
- .github/workflows/test.yml
- apps/server/src/routes/+layout.svelte
- docs/guides/deploy/latitude_cloud.mdx
- docs/sources/credentials.mdx
- packages/cli/src/cli.ts
- packages/cli/src/commands/cloud/secrets/add/index.ts
- packages/cli/src/commands/cloud/secrets/remove/index.ts
- packages/cli/src/lib/server/index.ts
- packages/cli/src/lib/telemetry/events.ts
- packages/cli/src/templates/dockerignore.template
We want to allow users to store safely this database credentials. This PR introduces a command for setting a secret linked to the app
https://github.com/latitude-dev/latitude/issues/347
> Add the ability for adding secrets to Latitude clould deployed apps

- .changeset/light-sloths-obey.md
- .github/pull_request_template.md
- packages/cli/src/commands/cloud/deploy/index.test.ts
- packages/cli/src/commands/cloud/deploy/index.ts
- packages/cli/src/lib/server/index.ts
- packages/cli/src/lib/telemetry/index.test.ts
- packages/cli/src/lib/telemetry/index.ts
When you attempt to deploy a latitude deploy without signing up or logging in, we display a nice message.
https://github.com/latitude-dev/latitude/assets/1948929/14b55ab0-9e93-42ca-9943-79fc5525b0dc
> minor: added signup/login message when attempting unauthorized deploy

- .changeset/clever-seas-cry.md
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
We were building CLI without proper env variables at build time for prereleases.
noop
> fix: cli production build on prerelease mode

- .changeset/spicy-crabs-scream.md
- apps/server/src/routes/api/queries/[...query]/+server.ts
- apps/server/src/routes/api/queries/[...query]/server.test.ts
We were adding a cache-control header that configured client-side caching but then we provided no way to invalidate this cache from the client. This hotfix removes the cache control header in order to ensure data is fresh. 
**Backend cache is still present**, so this change should result in minimal latency increase for users, in exchange for always-up-to-date data.
#381
> hotfix: http caching

- .changeset/chilled-donkeys-hunt.md
- .changeset/lazy-coins-enjoy.md
- apps/server/src/lib/errors/handler.ts
- packages/connectors/base/src/index.ts
- packages/connectors/base/src/supported_methods.test.ts
When we try to run a subquery with runQuery and its parent query has parameters, the db throws an error as we were passing parameters for the subquery that the db didn't know what to do with.
This commit fixes this issue.
https://github.com/latitude-dev/latitude/assets/1948929/5b2a2b3a-2ffb-4f4f-b880-63b56f5afdb7
> fix: runquery with parameters

- .changeset/neat-ravens-reflect.md
- packages/client/svelte/src/lib/internal/ui/chart/_Echarts.svelte
Updating the data loaded into a chart was still using some rows from the old query result, which made no sense.
Before fix:
https://github.com/latitude-dev/latitude/assets/57395395/9b672715-5209-4a5f-9482-a4bd0fd5bc5c
After fix:
https://github.com/latitude-dev/latitude/assets/57395395/b66ce44e-c60a-4960-bc89-c1a1fb827530
> Fix: Old data was leaking into chart after update

- .changeset/light-rats-exercise.md
- examples/sample-react/README.md
- packages/client/react/package.json
We were requiring *only* react 17 when in fact we can support any version from 16 upwards.
> minor: change react peer dependency on react package

- packages/client/svelte/package.json
- pnpm-lock.yaml
During the build process of our client/svelte package, the `build:css` process is executed, which compiles the tailwind styles into the `dist/styles.css` files, which is necessary for this package to be correctly imported.
Running the development environment of this package with `pnpm dev` breaks the exported files. This is because the dev mode runs `svelte-package --watch`, which rebuild the svelte package each time a svelte file changes. The problem with this is that, to rebuild it, it first removes all contents of the dist file, including `dist/styles.css`, but does not compile tailwind again afterwards.
Additionally, `build:css` is also called in watch mode, to update the styles file automatically too.
> Fix: svelte package dev watch mode

- .changeset/light-roses-begin.md
- packages/cli/src/cli.ts
- packages/cli/src/commands/dev/index.ts
- packages/cli/src/commands/telemetry/index.ts
- packages/cli/src/config.ts
- packages/cli/src/lib/installLatitudeServer.ts
- packages/cli/src/lib/server/index.ts
- packages/cli/src/lib/telemetry/index.test.ts
- packages/cli/src/lib/telemetry/index.ts
- packages/cli/src/templates/Dockerfile.ts
- packages/cli/src/templates/dockerignore.template
- packages/cli/tests/e2e/dev.cjs
- packages/cli/tests/e2e/start.cjs
This allows the cli to run commands where user input is not expected. Of course it won't apply to use cases where user input is expected.
https://github.com/latitude-dev/latitude/assets/1948929/08d9841d-4b05-4ffc-869c-8674a068f330
> feature: allow cli to work on non-tty envs

- .changeset/seven-beans-cover.md
- packages/cli/src/cli.ts
- packages/cli/src/commands/update/index.ts
- packages/cli/src/lib/addDockerfiles/fromUpdate.test.ts
- packages/cli/src/lib/addDockerfiles/fromUpdate.ts
- packages/cli/src/lib/updateApp/index.ts
Until now you had to pass a --force flag to update command in order to update docker-related config files. This was done to protect users' docker configs but in truth most people shouldn't be touching the docker configuration and it's a pita to have to pass this flag every time there's an update.
https://github.com/latitude-dev/latitude/assets/1948929/d9d0a79c-972c-4904-872d-fe1043170009
> feature: CLI update command updates dockerfiles

- .changeset/shiny-llamas-teach.md
- apps/server/src/lib/autoimports/forms/Select/index.svelte
- apps/server/src/lib/stores/queries.test.ts
- apps/server/src/lib/stores/queries.ts
computeQueryParameters was returning view parameters with undefined values which is not the desirable behaviour.
https://github.com/latitude-dev/latitude/assets/1948929/49422234-8d9a-425b-9758-87551b498dd6
> fix: undefined passed to query computations

- .changeset/selfish-buttons-rest.md
- packages/cli/src/lib/sync/syncQueries/ensureConnectorInstalled.test.ts
- packages/cli/src/lib/sync/syncQueries/ensureConnectorInstalled.ts
We now notify when a source file is invalid instead of harcrashing
fixes LATITUDE-DATA-CLI-R
https://github.com/latitude-dev/latitude/assets/1948929/3cd9f2d4-b5d7-4922-8e13-b43b2464a3ea
> fix: notify user when source file is invalid instead of hardcrashing

- .changeset/nasty-queens-draw.md
- packages/client/core/src/theme/skins/addDefaultAttributes.test.ts
- packages/client/core/src/theme/skins/addDefaultAttributes.ts
- packages/client/core/src/theme/skins/buildCssVariables.test.ts
- packages/client/core/src/theme/skins/buildEchartsTheme.test.ts
- packages/client/core/src/theme/skins/buildEchartsTheme.ts
- packages/client/core/src/theme/skins/index.ts
- packages/client/core/src/theme/skins/types.ts
- packages/client/core/src/theme/skins/utils.test.ts
- packages/client/core/src/theme/skins/utils.ts
Defining a simple theme sometimes can get annoying.
If the user just wants to change the background color from white to gray, they have not only to change `background`, but to change `card` too (every chart uses a card, and since it's the same color as the background by default it is not obvious that it needs to change), and `echarts.backgroundColor` (otherwise the chart background would still be white). Like this:
```json latitude.json
"theme": {
"background": "#CCC",
"card": "#CCC",
"echarts": {
"backgroundColor": "#CCC"
}
}
```
👆 This was just to change the background color... It gets worse with `foreground`.
To fix this, now some attributes inherit the value from other attributes. This means that, if the user only defines the `background` color, `card` and `echarts.backgroundColor` …
> Easier theme creation

- .changeset/mighty-taxis-know.md
- apps/server/scripts/run_query/index.ts
- apps/server/src/lib/constants.ts
- apps/server/src/lib/query_service/find_or_compute.test.ts
- apps/server/src/lib/server/sourceManager.test.ts
- apps/server/src/lib/server/sourceManager.ts
- apps/server/src/routes/api/queries/[...query]/server.test.ts
- apps/server/src/routes/api/queries/[...query]/specialParams.test.ts
- packages/connectors/materialized/src/index.test.ts
- packages/connectors/materialized/src/index.ts
- packages/connectors/materialized/src/tests/helpers.ts
- packages/source_manager/rollup.config.mjs
- packages/source_manager/src/index.ts
- packages/source_manager/src/manager/index.ts
- packages/source_manager/src/materialize/drivers/StorageDriver.ts
- packages/source_manager/src/materialize/drivers/disk/DiskDriver.test.ts
- packages/source_manager/src/materialize/drivers/disk/DiskDriver.ts
- packages/source_manager/src/materialize/drivers/dummy/DummyDriver.ts
- packages/source_manager/src/materialize/drivers/index.ts
- packages/source_manager/src/materialize/index.ts
- packages/source_manager/src/types.ts
When reading with DuckDB the parquet files from materialized queries we need a way of knowing where those queries are stored. We want to allow different ways of storing these parquet files. In this commit we start implementing the driver and the disk implementation that will be used almost always in development
https://github.com/latitude-dev/latitude/issues/369
> Materialize storage driver package

- .changeset/nasty-spies-argue.md
- packages/connectors/compiler/src/compiler/compiler.test.ts
- packages/connectors/compiler/src/compiler/index.ts
- packages/connectors/compiler/src/compiler/operators.ts
- packages/connectors/compiler/src/error/errors.ts
Compiler did not properly handle object properties. Before this commit, you could not:
- Invoke object properties as methods
- Modify object properties values
- Allow optional chaining operator (`?.`)
Some variable types can contain functions that may be useful in the query compilation run-time. A clear example is Dates, where a Date can be passed to a query as a param, and we may want to run date-related methods.
```
{minDate = param('start_date')}  -- Returns a Date object
SELECT *
FROM table
WHERE year >= {minDate.getYear()}   -- You can now run the .getYear() method from the date object!
```
You can now also modify the value from object properties such as arrays and hashes.
```
{ results = runQuery('other_query') }
{ results[0].name = 'foo' }  -- Modifying a property from an object …
```
> Fix: Properly handle object properties on Query Compiler

- .changeset/fresh-squids-yell.md
- .changeset/thick-singers-cover.md
- apps/server/src/lib/autoimports/forms/Select/index.svelte
- apps/server/src/lib/stores/viewParams.ts
- apps/server/src/routes/api/queries/[...query]/castValue.ts
- apps/server/src/routes/api/queries/[...query]/getQueryParams.ts
- docs/views/components/inputs/select.mdx
- packages/client/core/src/data/api.ts
- packages/client/svelte/src/lib/ui/combobox/index.svelte
- packages/custom_types/src/rich_date.ts
- packages/custom_types/src/type_parser.test.ts
- packages/custom_types/src/type_parser.ts
With the addition of the `multiple` prop, `Select` components can now support multiple item selection. When this prop is enabled, the associated parameter will be returned as an array, making them iterable from within queries. 
https://github.com/latitude-dev/latitude/assets/57395395/00e177ed-07ac-4568-956c-6de912cdc69c
Note: Select size is fixed in a different branch. Just ignore that for this PR.
> Feature: Multiple select support for Select component

- .github/workflows/pre-release.yml
- CONTRIBUTING.md
- packages/cli/src/cli.ts
- packages/cli/src/commands/start/index.ts
- packages/cli/src/commands/update/index.ts
- packages/cli/src/lib/getAppVersions.test.ts
- packages/cli/src/lib/getAppVersions.ts
- packages/cli/src/lib/latitudeConfig/create.ts
- packages/cli/src/lib/latitudeConfig/findOrCreate.ts
- packages/cli/src/lib/latitudeConfig/getLatestVersion.ts
- packages/cli/src/lib/setupApp/index.ts
I made these changes in `main` before https://github.com/latitude-dev/latitude/pull/443
But it doesn't make sense. We need these changes in canary to make the `.github/pre-release.yml` CI work and publish new canary versions I think
> Port pre-release adjustment from main to canary branch

- .changeset/brave-buses-beam.md
- package.json
- packages/cli/src/lib/telemetry/index.ts
- packages/client/react/rollup.config.mjs
- pnpm-lock.yaml
We want the CLI to continue working even when there's no internet or the telemetry system is not responding.
https://github.com/latitude-dev/latitude/issues/453
> Avoid breaking CLI because telemetry service is down

- .changeset/little-frogs-retire.md
- packages/cli/src/cli.ts
- packages/cli/src/commands/version/index.ts
☝️ That
https://github.com/latitude-dev/latitude/issues/452
I had to hack sade (our cli package) because I don't see a way of defining a custom version method. 
I opened an issue in their repo
https://github.com/lukeed/sade/issues/58
> Show app version and CLI version when running latitude -v

- .changeset/shaggy-stingrays-vanish.md
- packages/cli/src/commands/start/cloneTemplate.ts
We made a breaking change with the way we ref queries and we need to update the template. The problem is the person with access to the template repo is available so we would use another repo temporarily
> Temporary change template url

- .changeset/flat-meals-compete.md
- .changeset/tasty-chicken-knock.md
- packages/connectors/athena/src/index.ts
- packages/connectors/mssql/src/index.ts
- packages/source_manager/src/baseConnector/index.ts
Materializing queries currently requires fetching them in batches, but only the PostgreSQL connector has a ﻿`batchQuery` implementation. This means that any other source will fail if attempted.
Added a default `paginateQuery` function to the Base Connector that wraps any given query with a LIMIT and an OFFSET. Connectors may redefine this function if their syntax is different.
Then, added a default `batchQuery` implementation, where it just runs paginated queries one by one to the source until no more results are returned.
Not the most efficient process, but it's now supported by any connector! We can still redefine the `batchQuery` method for specific connectors to improve them one by one if we need so.
> Batch query support batch for any connectors

- .changeset/brave-carpets-drum.md
- packages/connectors/compiler/src/compiler/compile.test.ts
- packages/connectors/compiler/src/compiler/index.ts
- packages/connectors/compiler/src/compiler/logic/nodes/arrayExpression.ts
- packages/connectors/compiler/src/compiler/logic/nodes/objectExpression.ts
- packages/connectors/compiler/src/compiler/utils.ts
- packages/connectors/compiler/src/error/errors.ts
Added spread support on queries custom logic.
Also, improved `#each` block to support any iterator element, not just Arrays and Strings.
```jsx
{ selectedCities = param('cities_selector', []) }
{ cities = [  'bcn', 'nyc', ...selectedCities ] } /* Array created using spread */
SELECT *
FROM users
WHERE city IN (
{#each cities as name, index}
{name} {#if index == cities.length - 1} , {/if}
{/each}
)
```
> Compiler spread support

- .changeset/angry-planes-collect.md
- packages/client/react/.eslintrc.cjs
- packages/client/react/package.json
- packages/client/react/src/MainProvider.tsx
- packages/client/react/src/data/useQuery.ts
- packages/client/react/src/lib/ui/column/index.tsx
- pnpm-lock.yaml
- pnpm-workspace.yaml
Some users are still in older versions of React like React 16 or 17. We
moved back to react-query@v4 because v5 was using `useAsyncExternalStore`. We want to be more backwards compatible
I tested it with our [sample-react](https://github.com/latitude-dev/sample-react) which I also [had to change](https://github.com/latitude-dev/sample-react/commit/a2f618f94baf7e08dda62f6aa54a808484aa8c36)
> Downgrade react query from v5 to v4 

- .changeset/twelve-bottles-attend.md
- packages/cli/core/src/cli.ts
- packages/cli/core/src/commands/start/cloneTemplate.ts
- packages/cli/core/src/commands/version/index.ts
We did a refactor of the Latitude --version command and we broke the use case of just showing the CLI version when the user is not in a latitude project. Now we check if there is a latitude.json file in the folder before showing latitude.json app version and installed version.
```
latitude -v
```
Display this outside a latitude project 
After the fix show just the CLI version
> Fix showing latitude -v version outside a latitude app

- .changeset/short-wasps-nail.md
- packages/connectors/bigquery/src/index.ts
Getting Date/DateTime columns with null results no longer throws an error
> Fix: Handle nullable datetimes in BigQuery

- .changeset/swift-ligers-nail.md
- packages/cli/core/src/cli.ts
Instead of removing all warning events, I added a middleware that filters out only deprecation warnings, and keeps any other.
> CLI: Only ignore deprecation warnings

- .changeset/eighty-yaks-happen.md
- .changeset/lovely-apricots-bake.md
- packages/connectors/duckdb/.gitignore
- packages/connectors/duckdb/package.json
- packages/connectors/duckdb/src/data_types.test.ts
- packages/connectors/duckdb/src/index.ts
- packages/connectors/duckdb/src/tests/dummyApp/source.yml
- packages/source_manager/src/manager/index.test.ts
- packages/source_manager/src/manager/index.ts
- pnpm-lock.yaml
DuckDB was returning all result fields as "strings". Now it actually reads the types from the query result.
Before vs after:
https://github.com/latitude-dev/latitude/assets/57395395/070bb7a1-f381-4d0a-9921-ceaae202b6ac
> Fix: Data types for DuckDB

- .changeset/wet-bikes-check.md
- apps/server/scripts.rollup.config.mjs
- apps/server/scripts/materialize_queries/index.ts
- apps/server/src/lib/server/storageDriver.ts
- apps/server/vite.config.ts
- packages/cli/display_table/rollup.config.mjs
- packages/source_manager/rollup.config.mjs
- packages/source_manager/src/index.ts
- packages/source_manager/src/manager/index.ts
- packages/source_manager/src/source/readConfig.ts
- packages/source_manager/src/types.ts
- packages/source_manager/src/utils/index.test.ts
- packages/source_manager/src/utils/index.ts
- packages/storage_driver/rollup.config.mjs
- packages/storage_driver/src/drivers/base.ts
- packages/storage_driver/src/drivers/disk/index.ts
- packages/storage_driver/src/drivers/s3/index.ts
- pnpm-lock.yaml
We want to use some methods from these 2 packages in our Latitude cloud and we have to make it work.
> Some adjustments for Storage Driver and SourceManager to run on the cloud

- .changeset/cuddly-baboons-help.md
- packages/source_manager/src/manager/findAndMaterializeQueries.test.ts
- packages/source_manager/src/manager/index.ts
- packages/storage_driver/src/drivers/base.ts
- packages/storage_driver/src/drivers/disk/DiskDriver.test.ts
- packages/storage_driver/src/drivers/disk/index.ts
- packages/storage_driver/src/drivers/s3/index.ts
To avoid keeping broken parquet files, or displaying errors while re-materializing queries, the materialization process will create the parquet files in temp directories. Only when the materialization finished successfully, then the temp file will be moved to the final path where it has to be stored.
> Temp parquet files

- .changeset/wise-cheetahs-develop.md
- packages/cli/display_table/package.json
- packages/cli/display_table/src/components/CompiledQueryDisplay.tsx
- packages/cli/display_table/src/components/ErrorDisplay.tsx
- packages/cli/display_table/src/components/Scrollable.tsx
- packages/cli/display_table/src/components/Table.tsx
- pnpm-lock.yaml
A collection of bugfixes for the table component of the `latitude run` command.
Before|After
-------|-------
Before|After
-------|-------
> CLI Table fixes

- .changeset/pre.json
- packages/cli/core/CHANGELOG.md
- packages/cli/core/package.json
Check: `error: pathspec 'changeset-release/canary' did not match any file(s) known to git`
```bash
3s
Run changesets/action@v[1](https://github.com/latitude-dev/latitude/actions/runs/9662036083/job/26651507893#step:5:1)
setting git user
/usr/bin/git config user.name "github-actions[bot]"
/usr/bin/git config user.email "github-actions[bot]@users.noreply.github.com"
setting GitHub credentials
/usr/bin/git checkout changeset-release/canary
error: pathspec 'changeset-release/canary' did not match any file(s) known to git
/usr/bin/git checkout -b changeset-release/canary
Switched to a new branch 'changeset-release/canary'
/usr/bin/git reset --hard c2802e47262022bc497b21a286a6cac4ab912a3c
HEAD is now at c2802e4 Some fixes to make cloud deploy work (#530) …
```
> Version Packages (canary)

- .changeset/quiet-rings-double.md
- package.json
- packages/connectors/mysql/package.json
- packages/connectors/mysql/rollup.config.mjs
- packages/connectors/mysql/src/index.test.ts
- packages/connectors/mysql/src/index.ts
- pnpm-lock.yaml
Mysql connector uses mysql2 now instead of MySQL. This unlocks seamless connections to MySQL 8+ versions.
#173
> feature: move to mysql2

- packages/cli/core/src/commands/version/index.ts
- packages/cli/core/src/lib/setupApp/cloneAppFromNpm.ts
CLI is not detecting the installed version correctly. This makes the CLI always update to the latest version. The problem is that we're reading the version from the Latitude Project's root package.json, instead of the `.latitude/app` package.json
> Fix cli version checking

- .changeset/olive-oranges-glow.md
- packages/connectors/postgresql/src/index.ts
- packages/query_result/src/index.ts
- packages/source_manager/src/manager/parquetUtils.ts
While doing some tests with materialize I saw we don't treat JSONB columns as jsonb so I added a new data type for it
> Support materialize tables with JSONB fields

- .changeset/wicked-dolphins-raise.md
- packages/cli/core/src/lib/sync/syncPrompts/index.test.ts
- packages/cli/core/src/lib/sync/syncPrompts/index.ts
Fix this issue:
https://latitude-l5.sentry.io/issues/5542712717/?alert_rule_id=15084066&alert_type=issue&environment=production&notification_uuid=aa57f84a-01a5-4227-ae23-1b5679f76654&project=4506981816401920&referrer=slack
> Fix build when prompts folder does not exists

- packages/connectors/athena/src/index.ts
Fixed a bug that was cutting off of the last row of Athena results and corrected the row count for these results. 
#553 
https://github.com/user-attachments/assets/b66d1ddd-e56b-4b7b-961d-c9aab27f9ab0
> Do not cut off last athena ResultSet row
